### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by tjkemper**
Run postgres in a container.  Connect postgres and the api using *docker-compose*

Branched because we're not done (if we go this route). What do you think?

### up
```
docker-compose up -d
```

Postgres needs some time to set up. API may fail to connect. May have to wait 20 seconds and run:
```
docker-compose restart api
```

### down
```
docker-compose down
```

## SQL scripts

Notice the only sql scripts we need are located in `sql/`

### CODE REVIEW

**Comment by tjkemper** [comment]
@cmatheny

**Comment by cmatheny** [comment]
That would be easier to set up instead of installing postgres manually. My only concern is that any changes made to the local dev database are lost along with the container, meaning if you want to add some specific test data to your own database you have to do it each time you spin up the database. Is that something we can/want to address?

**Comment by tjkemper** [comment]
@cmatheny 
Database data is persisted in a volume (mounted at `./pgdata`).  **First time** you spin up environment, postgres will run the scripts in `./sql`.  Each time after, postgres will reuse data in the `./pgdata` volume.

**Spin up dev environment**
```
make up
```

**During development - rebuild api**
```
make
```

**Shut down dev environment**
```
make down
```

**Reset dev environment**
```
make clean
```

**Comment by tjkemper** [comment]
### One caveat
If it's your first time running `make up` or you are running it right after `make clean`, then Postgres needs some time to set up the database.

The API will initially fail to connect.  Wait 10-20 seconds and run `make`.

**Check the API logs**
```
make logs
```

**Comment by tjkemper** [comment]
### Another caveat

If our tests require specific data, then we must edit the scripts in `./sql`

Then everyone else just has to pull that code, `make clean`, and `make up`

**Comment by cmatheny** [comment]
I was getting permissions errors with the mounted database folder being on a windows filesystem. Solved by using a docker volume which persists after containers are stopped. Verified changes persisted through complete pc reboot. The volume is created if it doesn't yet exist, or mounted if it already exists. I also updated make clean to delete the volume. Do you see any problems with this setup?

**Comment by tjkemper** [comment]
lgtm

**Pull request merged**
